package org.codrshi.metric;

public enum MetricType {
    FILE_TRAVERSAL,
    FILE_PROCESSING,
    CHROMA_GET_OR_CREATE_COLLECTION,
    CHROMA_DELETE_COLLECTION,
    CHROMA_SAVE_EMBEDDINGS,
    CHROMA_SEARCH_EMBEDDINGS,
    CHROMA_DELETE_EMBEDDINGS,
    CHROMA_HEARTBEAT,
    OLLAMA_CREATE_EMBEDDINGS,
    OLLAMA_PS,
    LLM_GENERATE_SUMMARY,
    SQLITE_QUERY
}
